title: Site

# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.


# The layout of this form has three columns:
columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/3
    sections:
      thinking: sections/thinking

  # The second column has two sections, `notes` and `pages`
  - width: 1/3
    sections:
      # The `notes` section reuses the pages section defined in `/site/blueprints/sections/notes.yml`
      notes: sections/building

  # The third column has two sections, `notes` and `pages`
  - width: 1/3
    sections:
      # The `notes` section reuses the pages section defined in `/site/blueprints/sections/notes.yml`
      writing: sections/writing

      # The `pages` pages section shows other main pages of the site
      # Using the `templates` option, we limit which types of pages are shown
      # Using the `create` option, we limit the type of page that can be created when a new page is created
      # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
      # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list

      pages:
        label: Pages
        type: pages
        create: default
        templates:
          - about
          - home
          - default

      contact:
        label: Contact
        type: fields
        fields:
          title:
            label: Title
            type:  text
          phone:
            label: Phone Number
            type:  text
          email:
            label: Email
            type:  text
          address:
            label: Address
            type:  text
          instagram:
            label: Instagram
            type:  text